--- STEAMODDED HEADER
--- MOD_NAME: EclipseTextures
--- MOD_ID: eclipse
--- MOD_AUTHOR: [aleksxar]
--- MOD_DESCRIPTION: Aims to give most of the game's textures a dark mode makeover, without many changes to the vanilla look.

----------------------------------------------
------------MOD CODE -------------------------

function SMODS.INIT.EclipseTextures()

    local tpt_mod = SMODS.findModByID("eclipse")
    local sprite_vouchers = SMODS.Sprite:new("Voucher", tpt_mod.path, "Vouchers.png", 71, 95, "asset_atli")
    local sprite_deck1 = SMODS.Sprite:new("cards_1", tpt_mod.path, "8BitDeck.png", 71, 95, "asset_atli")
    local sprite_deck2 = SMODS.Sprite:new("cards_2", tpt_mod.path, "8BitDeck_opt2.png", 71, 95, "asset_atli")
    local sprite_logo = SMODS.Sprite:new("balatro", tpt_mod.path, "balatro.png", 333, 216, "asset_atli")
    local sprite_enhancers = SMODS.Sprite:new("centers", tpt_mod.path, "Enhancers.png", 71, 95, "asset_atli")
    local sprite_shop = SMODS.Sprite:new("shop_sign", tpt_mod.path, "ShopSignAnimation.png", 113, 57, "animation_atli", 4)
    local sprite_tags = SMODS.Sprite:new("tags", tpt_mod.path, "tags.png", 34, 34, "asset_atli")
    local sprite_tarots = SMODS.Sprite:new("Tarot", tpt_mod.path, "Tarots.png", 71, 95, "asset_atli")
    local sprite_ui1 = SMODS.Sprite:new("ui_1", tpt_mod.path, "ui_assets.png", 18, 18, "asset_atli")
    local sprite_ui2 = SMODS.Sprite:new("ui_2", tpt_mod.path, "ui_assets_opt2.png", 18, 18, "asset_atli")
    local sprite_jkr = SMODS.Sprite:new("Joker", tpt_mod.path, "Jokers.png", 71, 95, "asset_atli")
    local sprite_collab_au1 = SMODS.Sprite:new("collab_AU_1", tpt_mod.path, "collabs/collab_AU_1.png", 71, 95, "asset_atli")
    local sprite_collab_au2 = SMODS.Sprite:new("collab_AU_2", tpt_mod.path, "collabs/collab_AU_2.png", 71, 95, "asset_atli")
    local sprite_collab_tw1 = SMODS.Sprite:new("collab_TW_1", tpt_mod.path, "collabs/collab_TW_1.png", 71, 95, "asset_atli")
    local sprite_collab_tw2 = SMODS.Sprite:new("collab_TW_2", tpt_mod.path, "collabs/collab_TW_2.png", 71, 95, "asset_atli")
    local sprite_collab_vs1 = SMODS.Sprite:new("collab_VS_1", tpt_mod.path, "collabs/collab_VS_1.png", 71, 95, "asset_atli")
    local sprite_collab_vs2 = SMODS.Sprite:new("collab_VS_2", tpt_mod.path, "collabs/collab_VS_2.png", 71, 95, "asset_atli")
    local sprite_collab_dtd1 = SMODS.Sprite:new("collab_DTD_1", tpt_mod.path, "collabs/collab_DTD_1.png", 71, 95, "asset_atli")
    local sprite_collab_dtd2 = SMODS.Sprite:new("collab_DTD_2", tpt_mod.path, "collabs/collab_DTD_2.png", 71, 95, "asset_atli")
    local sprite_collab_cyp1 = SMODS.Sprite:new("collab_CYP_1", tpt_mod.path, "collabs/collab_CYP_1.png", 71, 95, "asset_atli")
    local sprite_collab_cyp2 = SMODS.Sprite:new("collab_CYP_2", tpt_mod.path, "collabs/collab_CYP_2.png", 71, 95, "asset_atli")
    local sprite_collab_sts1 = SMODS.Sprite:new("collab_STS_1", tpt_mod.path, "collabs/collab_STS_1.png", 71, 95, "asset_atli")
    local sprite_collab_sts2 = SMODS.Sprite:new("collab_STS_2", tpt_mod.path, "collabs/collab_STS_2.png", 71, 95, "asset_atli")
    local sprite_collab_tboi1 = SMODS.Sprite:new("collab_TBoI_1", tpt_mod.path, "collabs/collab_TBoI_1.png", 71, 95, "asset_atli")
    local sprite_collab_tboi2 = SMODS.Sprite:new("collab_TBoI_2", tpt_mod.path, "collabs/collab_TBoI_2.png", 71, 95, "asset_atli")
    local sprite_collab_sv1 = SMODS.Sprite:new("collab_SV_1", tpt_mod.path, "collabs/collab_SV_1.png", 71, 95, "asset_atli")
    local sprite_collab_sv2 = SMODS.Sprite:new("collab_SV_2", tpt_mod.path, "collabs/collab_SV_2.png", 71, 95, "asset_atli")
    local sprite_collab_cl1 = SMODS.Sprite:new("collab_CL_2", tpt_mod.path, "collabs/collab_CL_1.png", 71, 95, "asset_atli")
    local sprite_collab_cl2 = SMODS.Sprite:new("collab_CL_2", tpt_mod.path, "collabs/collab_CL_2.png", 71, 95, "asset_atli")
    local sprite_collab_d21 = SMODS.Sprite:new("collab_D2_1", tpt_mod.path, "collabs/collab_D2_1.png", 71, 95, "asset_atli")
    local sprite_collab_d22 = SMODS.Sprite:new("collab_D2_2", tpt_mod.path, "collabs/collab_D2_2.png", 71, 95, "asset_atli")
    local sprite_collab_ds1 = SMODS.Sprite:new("collab_DS_1", tpt_mod.path, "collabs/collab_DS_1.png", 71, 95, "asset_atli")
    local sprite_collab_ds2 = SMODS.Sprite:new("collab_DS_2", tpt_mod.path, "collabs/collab_DS_2.png", 71, 95, "asset_atli")
    local sprite_collab_eg1 = SMODS.Sprite:new("collab_EG_1", tpt_mod.path, "collabs/collab_EG_1.png", 71, 95, "asset_atli")
    local sprite_collab_eg2 = SMODS.Sprite:new("collab_EG_2", tpt_mod.path, "collabs/collab_EG_2.png", 71, 95, "asset_atli")
    local sprite_collab_pc1 = SMODS.Sprite:new("collab_PC_1", tpt_mod.path, "collabs/collab_PC_1.png", 71, 95, "asset_atli")
    local sprite_collab_pc2 = SMODS.Sprite:new("collab_PC_2", tpt_mod.path, "collabs/collab_PC_2.png", 71, 95, "asset_atli")
    local sprite_collab_sk1 = SMODS.Sprite:new("collab_SK_1", tpt_mod.path, "collabs/collab_SK_1.png", 71, 95, "asset_atli")
    local sprite_collab_sk2 = SMODS.Sprite:new("collab_SK_2", tpt_mod.path, "collabs/collab_SK_2.png", 71, 95, "asset_atli")
    local sprite_collab_wf1 = SMODS.Sprite:new("collab_WF_1", tpt_mod.path, "collabs/collab_WF_1.png", 71, 95, "asset_atli")
    local sprite_collab_wf2 = SMODS.Sprite:new("collab_WF_2", tpt_mod.path, "collabs/collab_WF_2.png", 71, 95, "asset_atli")
    local sprite_collab_xr1 = SMODS.Sprite:new("collab_XR_1", tpt_mod.path, "collabs/collab_XR_1.png", 71, 95, "asset_atli")
    local sprite_collab_xr2 = SMODS.Sprite:new("collab_XR_2", tpt_mod.path, "collabs/collab_XR_2.png", 71, 95, "asset_atli")

    sprite_vouchers:register()
    sprite_deck1:register()
    sprite_deck2:register()
    sprite_logo:register()
    sprite_enhancers:register()
    sprite_shop:register()
    sprite_tags:register()
    sprite_tarots:register()
    sprite_ui1:register()
    sprite_ui2:register()
    sprite_jkr:register()
    sprite_collab_au1:register()
    sprite_collab_au2:register()
    sprite_collab_tw1:register()
    sprite_collab_tw2:register()
    sprite_collab_vs1:register()
    sprite_collab_vs2:register()
    sprite_collab_dtd1:register()
    sprite_collab_dtd2:register()
    sprite_collab_cyp1:register()
    sprite_collab_cyp2:register()
    sprite_collab_sts1:register()
    sprite_collab_sts2:register()
    sprite_collab_tboi1:register()
    sprite_collab_tboi2:register()
    sprite_collab_sv1:register()
    sprite_collab_sv2:register()
    sprite_collab_cl1:register()
    sprite_collab_cl2:register()
    sprite_collab_d21:register()
    sprite_collab_d22:register()
    sprite_collab_ds1:register()
    sprite_collab_ds2:register()
    sprite_collab_eg1:register()
    sprite_collab_eg2:register()
    sprite_collab_pc1:register()
    sprite_collab_pc2:register()
    sprite_collab_sk1:register()
    sprite_collab_sk2:register()
    sprite_collab_wf1:register()
    sprite_collab_wf2:register()
    sprite_collab_xr1:register()
    sprite_collab_xr2:register()
end

----------------------------------------------
------------MOD CODE END----------------------
